include:
  - board: nrfmicro_13
    shield: corne_left
  - board: nrfmicro_13
    shield: corne_right
  - board: nrfmicro_13
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: tbk_left
  - board: seeeduino_xiao_ble
    shield: tbk_right
  - board: sparkfun_pro_micro_rp2040
    shield: choctopus44
